{application, erlog,
 [{description, "Erlog , Prolog in Erlang"},
  {vsn, "0.6"},
  {modules, [erlog,
	     erlog_bips,
	     erlog_boot,
	     erlog_dcg,
	     erlog_demo,
	     erlog_ets,
	     erlog_file,
	     erlog_int,
	     erlog_io,
	     erlog_lists,
	     erlog_parse,
	     erlog_scan,
	     erlog_shell
	    ]},
  {registered, []},
  {applications, [kernel,stdlib]}
 ]}.
