-file("/usr/lib/erlang/lib/parsetools-2.0.7/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(erlog_scan).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/erlog_scan.xrl", 75).

%% Copyright (c) 2008-2013 Robert Virding
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%     http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.

%% File    : erlog_scan.erl
%% Author  : Robert Virding
%% Purpose : Token definitions for Erlog.

-import(string, [substr/2,substr/3]).

%% base(Line, Chars, Base) -> Integer.
%% Convert a string of Base characters into a number. We know that
%% the strings only contain the correct character.

base(L, Cs, B) ->
    case base1(Cs, B, 0) of
	{N,[]} -> {token,{number,L,N}};
	{_,_} -> {error,"illegal based number"}
    end.

base1([C|Cs], Base, SoFar) when C >= $0, C =< $9, C < Base + $0 ->
    Next = SoFar * Base + (C - $0),
    base1(Cs, Base, Next);
base1([C|Cs], Base, SoFar) when C >= $a, C =< $f, C < Base + $a - 10 ->
    Next = SoFar * Base + (C - $a + 10),
    base1(Cs, Base, Next);
base1([C|Cs], Base, SoFar) when C >= $A, C =< $F, C < Base + $A - 10 ->
    Next = SoFar * Base + (C - $A + 10),
    base1(Cs, Base, Next);
base1([C|Cs], _Base, SoFar) -> {SoFar,[C|Cs]};
base1([], _Base, N) -> {N,[]}.

%% chars(InputChars) -> Chars.
%% Convert an input string into the corresponding string
%% characters. We know that the input string is correct.

chars([$\\,$x,C|Cs0]) ->
    case hex_char(C) of
	true ->
	    case base1([C|Cs0], 16, 0) of
		{N,[$\\|Cs1]} -> [N|chars(Cs1)];
		_Other -> [escape_char($x)|chars([C|Cs0])]
	    end;
	false -> [escape_char($x)|chars([C|Cs0])]
    end;
chars([$\\,C|Cs0]) when C >= $0, C =< $7 ->
    case base1(Cs0, 8, C - $0) of
	{N,[$\\|Cs1]} -> [N|chars(Cs1)];
	_Other -> [escape_char(C)|chars(Cs0)]
    end;
chars([$\\,C|Cs]) -> [escape_char(C)|chars(Cs)];
chars([C|Cs]) -> [C|chars(Cs)];
chars([]) -> [].

hex_char(C) when C >= $0, C =< $9 -> true;
hex_char(C) when C >= $a, C =< $f -> true;
hex_char(C) when C >= $A, C =< $F -> true;
hex_char(_) -> false.

escape_char($n) -> $\n;				%\n = LF
escape_char($r) -> $\r;				%\r = CR
escape_char($t) -> $\t;				%\t = TAB
escape_char($v) -> $\v;				%\v = VT
escape_char($b) -> $\b;				%\b = BS
escape_char($f) -> $\f;				%\f = FF
escape_char($e) -> $\e;				%\e = ESC
escape_char($s) -> $\s;				%\s = SPC
escape_char($d) -> $\d;				%\d = DEL
escape_char(C) -> C.

-file("/usr/lib/erlang/lib/parsetools-2.0.7/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L1, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L1, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L1, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/erlog_scan.erl", 356).
yystate() -> 60.

yystate(67, [42|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 0, Tlen);
yystate(67, [10|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line+1, Tlen+1, 0, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(61, Ics, Line, Tlen+1, 0, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 41 ->
    yystate(61, Ics, Line, Tlen+1, 0, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 43 ->
    yystate(61, Ics, Line, Tlen+1, 0, Tlen);
yystate(67, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,67};
yystate(66, [126|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [94|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [92|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [58|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [42|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [43|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [38|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [35|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [36|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 45, C =< 47 ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 64 ->
    yystate(3, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,66};
yystate(65, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 91 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(65, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,65};
yystate(64, [47|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 2, Tlen);
yystate(64, [40|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 2, Tlen);
yystate(64, [37|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(64, [10|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line+1, Tlen+1, 2, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(64, Ics, Line, Tlen+1, 2, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(64, Ics, Line, Tlen+1, 2, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,64};
yystate(63, [49|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 5, Tlen);
yystate(63, [48|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 5, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,63};
yystate(62, [126|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [94|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [93|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [92|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [59|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [58|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [47|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [45|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [46|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [44|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [43|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [42|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [38|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [37|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [35|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [36|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [10|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line+1, Tlen+1, 12, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 34 ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 39, C =< 41 ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 64 ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 91 ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 125 ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,62};
yystate(61, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line+1, Tlen+1, Action, Alen);
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 43 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(61, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,61};
yystate(60, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line+1, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 32 ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 60, C =< 64 ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 123, C =< 125 ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, [47|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 2, Tlen);
yystate(59, [42|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 2, Tlen);
yystate(59, [40|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 2, Tlen);
yystate(59, [37|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(59, [10|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line+1, Tlen+1, 2, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 41 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,59};
yystate(58, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line+1, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 43, C =< 46 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 48 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(58, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,58};
yystate(57, [120|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 8, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 47 ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 55 ->
    yystate(29, Ics, Line, Tlen+1, 8, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 56, C =< 119 ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 121 ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,57};
yystate(56, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(55, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(55, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(55, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,55};
yystate(54, [126|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [94|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [93|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [92|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [59|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [58|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [44|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [43|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [42|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [38|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [37|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [35|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [36|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [10|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line+1, Tlen+1, 12, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 34 ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 39, C =< 41 ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 45, C =< 47 ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 64 ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 91 ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 125 ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(50, Ics, Line, Tlen+1, 12, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,54};
yystate(53, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line+1, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 43, C =< 46 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 48 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(53, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,53};
yystate(52, [95|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(52, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(52, Ics, Line, Tlen+1, 9, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,52};
yystate(51, [47|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 2, Tlen);
yystate(51, [42|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(51, [41|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(51, [40|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 2, Tlen);
yystate(51, [38|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(51, [39|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(51, [37|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(51, [10|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line+1, Tlen+1, 2, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 36 ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,51};
yystate(50, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line+1, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(50, [C|Ics], Line, Tlen, Action, Alen) when C >= 43 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(50, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,50};
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, 8, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(41, Ics, Line, Tlen+1, 8, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(41, Ics, Line, Tlen+1, 8, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,49};
yystate(48, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(48, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(48, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line+1, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(48, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(48, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,48};
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 55 ->
    yystate(47, Ics, Line, Tlen+1, 6, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,47};
yystate(46, [126|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(46, [94|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(46, [92|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(46, [58|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(46, [43|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(46, [42|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 12, Tlen);
yystate(46, [38|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(46, [35|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(46, [36|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 45, C =< 47 ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 64 ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,46};
yystate(45, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line+1, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 43 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(45, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,45};
yystate(44, [95|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 14, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(44, Ics, Line, Tlen+1, 14, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(44, Ics, Line, Tlen+1, 14, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(44, Ics, Line, Tlen+1, 14, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,44};
yystate(43, [47|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 0, Tlen);
yystate(43, [42|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 0, Tlen);
yystate(43, [40|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 0, Tlen);
yystate(43, [37|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(43, [10|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line+1, Tlen+1, 0, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 41 ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(27, Ics, Line, Tlen+1, 0, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,43};
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(42, Ics, Line, Tlen+1, 1, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 11 ->
    yystate(42, Ics, Line, Tlen+1, 1, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,42};
yystate(41, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(41, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,41};
yystate(40, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 55 ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,39};
yystate(38, [126|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [94|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [92|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [58|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [47|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [45|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [46|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [42|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [43|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [38|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [37|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [35|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [36|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [10|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line+1, Tlen+1, 12, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(34, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(34, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 64 ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,38};
yystate(37, [47|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(37, [42|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(37, [40|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 2, Tlen);
yystate(37, [37|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(37, [10|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line+1, Tlen+1, 2, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 41 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,37};
yystate(36, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(35, [47|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, [42|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, [41|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, [40|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, [38|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, [39|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, [37|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, [10|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line+1, Tlen+1, 2, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(35, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(35, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 36 ->
    yystate(61, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(61, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(61, Ics, Line, Tlen+1, 2, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,35};
yystate(34, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(33, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line};
yystate(32, [92|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 15, Tlen);
yystate(32, [34|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 15, Tlen);
yystate(32, [10|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line+1, Tlen+1, 15, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(48, Ics, Line, Tlen+1, 15, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(48, Ics, Line, Tlen+1, 15, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(48, Ics, Line, Tlen+1, 15, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(48, Ics, Line, Tlen+1, 15, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,32};
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(31, Ics, Line, Tlen+1, 7, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(31, Ics, Line, Tlen+1, 7, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(31, Ics, Line, Tlen+1, 7, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,31};
yystate(30, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(30, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,30};
yystate(29, [92|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 55 ->
    yystate(21, Ics, Line, Tlen+1, 8, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,29};
yystate(28, [46|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 4, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 4, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,28};
yystate(27, [47|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(27, [42|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 2, Tlen);
yystate(27, [40|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 2, Tlen);
yystate(27, [37|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(27, [10|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line+1, Tlen+1, 2, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 41 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(27, Ics, Line, Tlen+1, 2, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,27};
yystate(26, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(25, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line+1, Tlen+1, Action, Alen);
yystate(25, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(25, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(25, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,25};
yystate(24, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line+1, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 55 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 56, C =< 91 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(24, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,24};
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(23, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,23};
yystate(22, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line+1, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 43, C =< 46 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 48 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,22};
yystate(21, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 55 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(21, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,21};
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(20, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,20};
yystate(19, [47|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, [40|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, [38|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, [39|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, [37|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, [10|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line+1, Tlen+1, 0, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 36 ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 41, C =< 46 ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(11, Ics, Line, Tlen+1, 0, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,19};
yystate(18, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line+1, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 47 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 91 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(18, [C|Ics], Line, Tlen, Action, Alen) when C >= 103 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(18, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,18};
yystate(17, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(16, [120|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line+1, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 55 ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 56, C =< 91 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 119 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 121 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(16, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,16};
yystate(15, [120|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, [111|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, [98|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, [46|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, [39|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(28, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,15};
yystate(14, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(13, [126|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [94|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [92|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [58|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [43|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [42|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [38|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [35|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [36|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 45, C =< 47 ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 64 ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,13};
yystate(12, [101|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 3, Tlen);
yystate(12, [69|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 3, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(12, Ics, Line, Tlen+1, 3, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,12};
yystate(11, [47|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 2, Tlen);
yystate(11, [40|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 2, Tlen);
yystate(11, [38|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(11, [39|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(11, [37|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(11, [10|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line+1, Tlen+1, 2, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 33, C =< 36 ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 41, C =< 46 ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,11};
yystate(10, [126|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [94|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [92|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [58|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [47|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [45|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [46|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [42|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [43|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [40|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [38|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [37|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [35|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [36|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [10|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line+1, Tlen+1, 2, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(64, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(64, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 64 ->
    yystate(3, Ics, Line, Tlen+1, 2, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,10};
yystate(9, [92|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 13, Tlen);
yystate(9, [39|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 13, Tlen);
yystate(9, [10|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line+1, Tlen+1, 13, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(25, Ics, Line, Tlen+1, 13, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 38 ->
    yystate(25, Ics, Line, Tlen+1, 13, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 91 ->
    yystate(25, Ics, Line, Tlen+1, 13, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(25, Ics, Line, Tlen+1, 13, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,9};
yystate(8, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line+1, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 91 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 103 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(8, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,8};
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(7, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,7};
yystate(6, [120|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line+1, Tlen+1, Action, Alen);
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 47 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 55 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 56, C =< 91 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 119 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 121 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(6, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,6};
yystate(5, [126|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [94|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [93|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [92|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [59|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [58|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [44|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [43|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [42|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [38|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [37|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [35|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [36|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [10|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line+1, Tlen+1, 12, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 34 ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 39, C =< 41 ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 45, C =< 47 ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 64 ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 91 ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 125 ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,5};
yystate(4, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(4, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(4, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,4};
yystate(3, [126|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(3, [94|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(3, [92|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(3, [58|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(3, [42|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(3, [43|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(3, [38|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(3, [35|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(3, [36|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 45, C =< 47 ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 64 ->
    yystate(3, Ics, Line, Tlen+1, 12, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,3};
yystate(2, [126|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [94|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [93|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [92|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [59|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [58|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [47|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [45|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [46|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [44|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [43|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [42|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [38|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [37|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [35|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [36|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [10|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line+1, Tlen+1, 12, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 34 ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 39, C =< 41 ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 60, C =< 64 ->
    yystate(5, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 91 ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 95, C =< 125 ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 127 ->
    yystate(61, Ics, Line, Tlen+1, 12, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,2};
yystate(1, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line+1, Tlen+1, Action, Alen);
yystate(1, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 47 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 55 ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [C|Ics], Line, Tlen, Action, Alen) when C >= 56, C =< 91 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(1, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(1, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,1};
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(0, Ics, Line, Tlen+1, 3, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, TokenLine) ->
    yyaction_0(TokenLine);
yyaction(1, _, _, TokenLine) ->
    yyaction_1(TokenLine);
yyaction(2, _, _, _) ->
    yyaction_2();
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLen, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLen, TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("src/erlog_scan.xrl", 34).
yyaction_0(TokenLine) ->
     { token, { ' (', TokenLine } } .

-compile({inline,yyaction_1/1}).
-file("src/erlog_scan.xrl", 35).
yyaction_1(TokenLine) ->
     { end_token, { dot, TokenLine } } .

-compile({inline,yyaction_2/0}).
-file("src/erlog_scan.xrl", 36).
yyaction_2() ->
     skip_token .

-compile({inline,yyaction_3/2}).
-file("src/erlog_scan.xrl", 40).
yyaction_3(TokenChars, TokenLine) ->
     { token, { number, TokenLine, list_to_float (TokenChars) } } .

-compile({inline,yyaction_4/2}).
-file("src/erlog_scan.xrl", 41).
yyaction_4(TokenChars, TokenLine) ->
     { token, { number, TokenLine, list_to_integer (TokenChars) } } .

-compile({inline,yyaction_5/2}).
-file("src/erlog_scan.xrl", 42).
yyaction_5(TokenChars, TokenLine) ->
     base (TokenLine, string : substr (TokenChars, 3), 2) .

-compile({inline,yyaction_6/2}).
-file("src/erlog_scan.xrl", 43).
yyaction_6(TokenChars, TokenLine) ->
     base (TokenLine, string : substr (TokenChars, 3), 8) .

-compile({inline,yyaction_7/2}).
-file("src/erlog_scan.xrl", 44).
yyaction_7(TokenChars, TokenLine) ->
     base (TokenLine, string : substr (TokenChars, 3), 16) .

-compile({inline,yyaction_8/2}).
-file("src/erlog_scan.xrl", 46).
yyaction_8(TokenChars, TokenLine) ->
     { token, { number, TokenLine, hd (chars (string : substr (TokenChars, 3))) } } .

-compile({inline,yyaction_9/2}).
-file("src/erlog_scan.xrl", 49).
yyaction_9(TokenChars, TokenLine) ->
     { token, { atom, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_10/1}).
-file("src/erlog_scan.xrl", 50).
yyaction_10(TokenLine) ->
     { token, { atom, TokenLine, '!' } } .

-compile({inline,yyaction_11/1}).
-file("src/erlog_scan.xrl", 51).
yyaction_11(TokenLine) ->
     { token, { atom, TokenLine, ';' } } .

-compile({inline,yyaction_12/2}).
-file("src/erlog_scan.xrl", 52).
yyaction_12(TokenChars, TokenLine) ->
     { token, { atom, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_13/3}).
-file("src/erlog_scan.xrl", 55).
yyaction_13(TokenChars, TokenLen, TokenLine) ->
     S = string : substr (TokenChars, 2, TokenLen - 2),
     case catch list_to_atom (chars (S)) of
     { 'EXIT', _ } -> { error, "illegal atom " ++ TokenChars } ;
     Atom -> { token, { atom, TokenLine, Atom } }
     end .

-compile({inline,yyaction_14/2}).
-file("src/erlog_scan.xrl", 62).
yyaction_14(TokenChars, TokenLine) ->
     { token, { var, TokenLine, list_to_atom (TokenChars) } } .

-compile({inline,yyaction_15/3}).
-file("src/erlog_scan.xrl", 67).
yyaction_15(TokenChars, TokenLen, TokenLine) ->
     S = string : substr (TokenChars, 2, TokenLen - 2),
     { token, { string, TokenLine, chars (S) } } .

-compile({inline,yyaction_16/2}).
-file("src/erlog_scan.xrl", 71).
yyaction_16(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-file("/usr/lib/erlang/lib/parsetools-2.0.7/include/leexinc.hrl", 282).
